### ISSUE TITLE
Hey Woojae I have my full network up but Im getting timeout error on login using admin adminpw

### ISSUE THREAD

**Issue by elitekode2** [woojae9488/HLF_survey#3] opened 2020-04-26 13:56 UTC
Is there any way I could get in touch with you?

http://54.152.218.53:8080/#/Signin

**Comment by elitekode2** [comment] 2020-04-26 13:57
app is not loggin in with admin and adminpw?

Could this be a memory issue.

I checked orderer logs : 

> -channel' with genesis block hash 169a249575bd84e1b3dd1866d34b97203bdd899688a013eb57a2248607f49958 and orderer type solo
2020-04-26 13:20:44.846 UTC [orderer.common.server] Start -> INFO 006 Starting orderer:
 Version: 1.4.0
 Commit SHA: d700b43
 Go version: go1.11.1
 OS/Arch: linux/amd64
2020-04-26 13:20:44.846 UTC [orderer.common.server] Start -> INFO 007 Beginning to serve requests
2020-04-26 13:20:47.184 UTC [fsblkstorage] newBlockfileMgr -> INFO 008 Getting block information from block storage
2020-04-26 13:20:47.207 UTC [orderer.commmon.multichannel] newChain -> INFO 009 Created and starting new chain surveynet
2020-04-26 13:20:47.228 UTC [comm.grpc.server] 1 -> INFO 00a streaming call completed {"grpc.start_time": "2020-04-26T13:20:47.157Z", "grpc.service": "orderer.AtomicBroadcast", "grpc.method": "Broadcast", "grpc.peer_address": "172.18.0.9:47832", "grpc.code": "OK", "grpc.call_duration": "70.120322ms"}
2020-04-26 13:20:47.247 UTC [common.deliver] Handle -> WARN 00b Error reading from 172.18.0.9:47830: rpc error: code = Canceled desc = context canceled
2020-04-26 13:20:47.247 UTC [comm.grpc.server] 1 -> INFO 00c streaming call completed {"grpc.start_time": "2020-04-26T13:20:47.156Z", "grpc.service": "orderer.AtomicBroadcast", "grpc.method": "Deliver", "grpc.peer_address": "172.18.0.9:47830", "error": "rpc error: code = Canceled desc = context canceled", "grpc.code": "Canceled", "grpc.call_duration": "91.420481ms"}
2020-04-26 13:21:08.128 UTC [common.deliver] Handle -> WARN 00d Error reading from 172.18.0.9:47848: rpc error: code = Canceled desc = context canceled
2020-04-26 13:21:08.128 UTC [comm.grpc.server] 1 -> INFO 00e streaming call completed {"grpc.start_time": "2020-04-26T13:21:08.084Z", "grpc.service": "orderer.AtomicBroadcast", "grpc.method": "Deliver", "grpc.peer_address": "172.18.0.9:47848", "error": "rpc error: code = Canceled desc = context canceled", "grpc.code": "Canceled", "grpc.call_duration": "43.818512ms"}
2020-04-26 13:21:08.129 UTC [orderer.common.broadcast] Handle -> WARN 00f Error reading from 172.18.0.9:47850: rpc error: code = Canceled desc = context canceled
2020-04-26 13:21:08.129 UTC [comm.grpc.server] 1 -> INFO 010 streaming call completed {"grpc.start_time": "2020-04-26T13:21:08.086Z", "grpc.service": "orderer.AtomicBroadcast", "grpc.method": "Broadcast", "grpc.peer_address": "172.18.0.9:47850", "error": "rpc error: code = Canceled desc = context canceled", "grpc.code": "Canceled", "grpc.call_duration": "42.225994ms"}
2020-04-26 13:21:13.215 UTC [common.deliver] Handle -> WARN 011 Error reading from 172.18.0.9:47866: rpc error: code = Canceled desc = context canceled
2020-04-26 13:21:13.215 UTC [comm.grpc.server] 1 -> INFO 012 streaming call completed {"grpc.start_time": "2020-04-26T13:21:13.17Z", "grpc.service": "orderer.AtomicBroadcast", "grpc.method": "Deliver", "grpc.peer_address": "172.18.0.9:47866", "error": "rpc error: code = Canceled desc = context canceled", "grpc.code": "Canceled", "grpc.call_duration": "45.163141ms"}
2020-04-26 13:21:13.215 UTC [orderer.common.broadcast] Handle -> WARN 013 Error reading from 172.18.0.9:47868: rpc error: code = Canceled desc = context canceled
2020-04-26 13:21:13.215 UTC [comm.grpc.server] 1 -> INFO 014 streaming call completed {"grpc.start_time": "2020-04-26T13:21:13.172Z", "grpc.service": "orderer.AtomicBroadcast", "grpc.method": "Broadcast", "grpc.peer_address": "172.18.0.9:47868", "error": "rpc error: code = Canceled desc = context canceled", "grpc.code": "Canceled", "grpc.call_duration": "43.744056ms"}
2020-04-26 13:21:50.638 UTC [orderer.common.broadcast] Handle -> WARN 015 Error reading from 172.18.0.9:47910: rpc error: code = Canceled desc = context canceled
2020-04-26 13:21:50.638 UTC [comm.grpc.server] 1 -> INFO 016 streaming call completed {"grpc.start_time": "2020-04-26T13:21:18.456Z", "grpc.service": "orderer.AtomicBroadcast", "grpc.method": "Broadcast", "grpc.peer_address": "172.18.0.9:47910", "error": "rpc error: code = Canceled desc = context canceled", "grpc.code": "Canceled", "grpc.call_duration": "32.181942809s"}
2020-04-26 13:21:55.777 UTC [orderer.common.broadcast] Handle -> WARN 017 Error reading from 172.18.0.9:47954: rpc error: code = Canceled desc = context canceled
2020-04-26 13:21:55.777 UTC [comm.grpc.server] 1 -> INFO 018 streaming call completed {"grpc.start_time": "2020-04-26T13:21:55.724Z", "grpc.service": "orderer.AtomicBroadcast", "grpc.method": "Broadcast", "grpc.peer_address": "172.18.0.9:47954", "error": "rpc error: code = Canceled desc = context canceled", "grpc.code": "Canceled", "grpc.call_duration": "53.613628ms"}
2020-04-26 13:23:04.729 UTC [orderer.common.broadcast] Handle -> WARN 019 Error reading from 172.18.0.9:48000: rpc error: code = Canceled desc = context canceled
2020-04-26 13:23:04.734 UTC [comm.grpc.server] 1 -> INFO 01a streaming call completed {"grpc.start_time": "2020-04-26T13:22:32.179Z", "grpc.service": "orderer.AtomicBroadcast", "grpc.method": "Broadcast", "grpc.peer_address": "172.18.0.9:48000", "error": "rpc error: code = Canceled desc = context canceled", "grpc.code": "Canceled", "grpc.call_duration": "32.55544239s"}
2020-04-26 13:23:49.098 UTC [orderer.common.broadcast] Handle -> WARN 01b Error reading from 172.18.0.9:48038: rpc error: code = Canceled desc = context canceled
2020-04-26 13:23:49.100 UTC [comm.grpc.server] 1 -> INFO 01c streaming call completed {"grpc.start_time": "2020-04-26T13:23:09.995Z", "grpc.service": "orderer.AtomicBroadcast", "grpc.method": "Broadcast", "grpc.peer_address": "172.18.0.9:48038", "error": "rpc error: code = Canceled desc = context canceled", "grpc.code": "Canceled", "grpc.call_duration": "39.105215227s"}
2020-04-26 13:26:56.729 UTC [comm.grpc.server] 1 -> INFO 01d streaming call completed {"grpc.start_time": "2020-04-26T13:20:53.44Z", "grpc.service": "orderer.AtomicBroadcast", "grpc.method": "Deliver", "grpc.peer_address": "172.18.0.2:59048", "grpc.peer_subject": "CN=peer0.manager.jnu.com,L=San Francisco,ST=California,C=US", "error": "context finished before block retrieved: context canceled", "grpc.code": "Unknown", "grpc.call_duration": "6m3.292792521s"}
2020-04-26 13:29:25.266 UTC [comm.grpc.server] 1 -> INFO 01e streaming call completed {"grpc.start_time": "2020-04-26T13:21:03.83Z", "grpc.service": "orderer.AtomicBroadcast", "grpc.method": "Deliver", "grpc.peer_address": "172.18.0.7:34646", "grpc.peer_subject": "CN=peer0.student.jnu.com,L=San Francisco,ST=California,C=US", "error": "context finished before block retrieved: context canceled", "grpc.code": "Unknown", "grpc.call_duration": "8m21.517720392s"}
^Z

**Comment by woojae9488** [comment] 2020-04-26 14:38
Hmm... I don't know exactly what's wrong with these logs alone. If you think the problem is caused by lack of memory, you should first go into the client app and change the time limit for the timeout and read the results again. The environment I tested was the EC2 environment on AWS, where it worked well within a 10-second timeout!

The time-out change can be resolved in the following paths:
fabric-survey-app/web-app/client/src/services/api.js
And inside this file, try changing the timeout attribute in the instance() function to the desired ms! 
I hope there will be good results to find out the cause! 

P.S. And rather than looking at the log of the orderer, it would be a good choice to look at the log of the api-gateway or fabric-manager docker container. Good Luck!!!

**Comment by woojae9488** [comment] 2020-04-26 14:48
And if you want to contact me, I can reply right away if you use Korea's KakaoTalk app!

**Comment by elitekode2** [comment] 2020-04-26 15:27
Here are the logs for the api-gateway. I  still cant figure out the issues its says 500. 

BTW whats your KakaoTalk App ID?


`::ffff:75.7.143.32 - - [26/Apr/2020:13:35:54 +0000] "OPTIONS /v1/fabric/auth/token?role=manager HTTP/1.1" 204 0 "http://54.152.218.53:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:75.0) Gecko/20100101 Firefox/75.0"
::ffff:75.7.143.32 - - [26/Apr/2020:13:36:04 +0000] "POST /v1/fabric/auth/token?role=manager HTTP/1.1" - - "http://54.152.218.53:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:75.0) Gecko/20100101 Firefox/75.0"
::ffff:75.7.143.32 - - [26/Apr/2020:13:36:51 +0000] "OPTIONS /v1/fabric/auth/token?role=manager HTTP/1.1" 204 0 "http://54.152.218.53:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:75.0) Gecko/20100101 Firefox/75.0"
::ffff:75.7.143.32 - - [26/Apr/2020:13:37:01 +0000] "POST /v1/fabric/auth/token?role=manager HTTP/1.1" - - "http://54.152.218.53:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:75.0) Gecko/20100101 Firefox/75.0"
::ffff:75.7.143.32 - - [26/Apr/2020:13:37:05 +0000] "OPTIONS /v1/fabric/auth/token?role=student HTTP/1.1" 204 0 "http://54.152.218.53:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:75.0) Gecko/20100101 Firefox/75.0"
::ffff:75.7.143.32 - - [26/Apr/2020:13:37:15 +0000] "POST /v1/fabric/auth/token?role=student HTTP/1.1" - - "http://54.152.218.53:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:75.0) Gecko/20100101 Firefox/75.0"
::ffff:75.7.143.32 - - [26/Apr/2020:13:37:34 +0000] "OPTIONS /v1/fabric/auth/token?role=manager HTTP/1.1" 204 0 "http://54.152.218.53:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:75.0) Gecko/20100101 Firefox/75.0"
::ffff:75.7.143.32 - - [26/Apr/2020:13:37:44 +0000] "POST /v1/fabric/auth/token?role=manager HTTP/1.1" - - "http://54.152.218.53:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:75.0) Gecko/20100101 Firefox/75.0"
::ffff:75.7.143.32 - - [26/Apr/2020:13:38:06 +0000] "OPTIONS /v1/fabric/auth/token?role=manager HTTP/1.1" 204 0 "http://54.152.218.53:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:75.0) Gecko/20100101 Firefox/75.0"
::ffff:75.7.143.32 - - [26/Apr/2020:13:38:16 +0000] "POST /v1/fabric/auth/token?role=manager HTTP/1.1" - - "http://54.152.218.53:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:75.0) Gecko/20100101 Firefox/75.0"
::ffff:75.7.143.32 - - [26/Apr/2020:13:39:32 +0000] "OPTIONS /v1/fabric/auth/token?role=manager HTTP/1.1" 204 0 "http://54.152.218.53:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:75.0) Gecko/20100101 Firefox/75.0"
::ffff:75.7.143.32 - - [26/Apr/2020:13:39:32 +0000] "POST /v1/fabric/auth/token?role=manager HTTP/1.1" 401 67 "http://54.152.218.53:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:75.0) Gecko/20100101 Firefox/75.0"
::ffff:75.7.143.32 - - [26/Apr/2020:13:39:44 +0000] "OPTIONS /v1/fabric/auth/token?role=manager HTTP/1.1" 204 0 "http://54.152.218.53:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:75.0) Gecko/20100101 Firefox/75.0"
::ffff:75.7.143.32 - - [26/Apr/2020:13:39:54 +0000] "POST /v1/fabric/auth/token?role=manager HTTP/1.1" - - "http://54.152.218.53:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:75.0) Gecko/20100101 Firefox/75.0"
::ffff:75.7.143.32 - - [26/Apr/2020:13:41:36 +0000] "OPTIONS /v1/fabric/auth/token?role=manager HTTP/1.1" 204 0 "http://54.152.218.53:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:75.0) Gecko/20100101 Firefox/75.0"
::ffff:75.7.143.32 - - [26/Apr/2020:13:41:46 +0000] "POST /v1/fabric/auth/token?role=manager HTTP/1.1" - - "http://54.152.218.53:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:75.0) Gecko/20100101 Firefox/75.0"
::ffff:75.7.143.32 - - [26/Apr/2020:13:45:44 +0000] "OPTIONS /v1/fabric/auth/token?role=manager HTTP/1.1" 204 0 "http://54.152.218.53:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:75.0) Gecko/20100101 Firefox/75.0"
::ffff:75.7.143.32 - - [26/Apr/2020:13:45:54 +0000] "POST /v1/fabric/auth/token?role=manager HTTP/1.1" - - "http://54.152.218.53:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:75.0) Gecko/20100101 Firefox/75.0"
::ffff:75.7.143.32 - - [26/Apr/2020:13:47:23 +0000] "OPTIONS /v1/fabric/auth/token?role=manager HTTP/1.1" 204 0 "http://54.152.218.53:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:75.0) Gecko/20100101 Firefox/75.0"
::ffff:75.7.143.32 - - [26/Apr/2020:13:47:33 +0000] "POST /v1/fabric/auth/token?role=manager HTTP/1.1" - - "http://54.152.218.53:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:75.0) Gecko/20100101 Firefox/75.0"
::ffff:75.7.143.32 - - [26/Apr/2020:13:50:19 +0000] "OPTIONS /v1/fabric/auth/token?role=manager HTTP/1.1" 204 0 "http://54.152.218.53:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:75.0) Gecko/20100101 Firefox/75.0"
::ffff:75.7.143.32 - - [26/Apr/2020:13:50:29 +0000] "POST /v1/fabric/auth/token?role=manager HTTP/1.1" - - "http://54.152.218.53:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:75.0) Gecko/20100101 Firefox/75.0"
::ffff:211.198.195.77 - - [26/Apr/2020:14:28:25 +0000] "OPTIONS /v1/fabric/auth/token?role=manager HTTP/1.1" 204 0 "http://54.152.218.53:8080/" "Mozilla/5.0 (Linux; Android 6.0.1; LG-F700L) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Mobile Safari/537.36"
::ffff:211.198.195.77 - - [26/Apr/2020:14:28:35 +0000] "POST /v1/fabric/auth/token?role=manager HTTP/1.1" 500 58 "http://54.152.218.53:8080/" "Mozilla/5.0 (Linux; Android 6.0.1; LG-F700L) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Mobile Safari/537.36"
::ffff:211.198.195.77 - - [26/Apr/2020:14:30:07 +0000] "OPTIONS /v1/fabric/auth/token?role=manager HTTP/1.1" 204 0 "http://54.152.218.53:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36"
::ffff:211.198.195.77 - - [26/Apr/2020:14:30:17 +0000] "POST /v1/fabric/auth/token?role=manager HTTP/1.1" 500 58 "http://54.152.218.53:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36"`

**Comment by elitekode2** [comment] 2020-04-26 15:28
<img width="881" alt="Screen Shot 2020-04-26 at 11 28 12 AM" src="https://user-images.githubusercontent.com/36805232/80312046-1c2e9f00-87b1-11ea-8817-587d6cb497be.png">

**Comment by elitekode2** [comment] 2020-04-26 15:54
Im using a small sized EC2 1 cpu 2gb ram.

**Comment by elitekode2** [comment] 2020-04-26 19:52
I also see this. isnt this removing the admin user.. 

`peer chaincode invoke -o orderer.jnu.com:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/jnu.com/orderers/orderer.jnu.com/msp/tlscacerts/tlsca.jnu.com-cert.pem -C surveynet -n surveycc --peerAddresses peer1.student.jnu.com:10051 --tlsRootCertFiles /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/student.jnu.com/peers/peer1.student.jnu.com/tls/ca.crt -c '{"Args":["remove","전남대학교","0","admin"]}'`

**Comment by woojae9488** [comment] 2020-04-26 22:57
The last invoke command you sent me is to erase the survey registered as a test.
I've tested it with a free-tear of EC2, so I don't think the time-out on your EC2 is due to lack of memory.
And if you let me know your KakaoTalk App ID, I will add you as a friend and send you a message.

**Comment by elitekode2** [comment] 2020-04-27 00:05
My ID is **Ace** . 

Thanks for connecting with me its a big help.

**Comment by woojae9488** [comment] 2020-04-27 01:02
I'm sorry, but it says there's no such ID.
Is it the ID you used to log in to KakaoTalk, not your name?

**Comment by elitekode2** [comment] 2020-04-27 01:53
Just created one it’s ace24ft

**Comment by woojae9488** [comment] 2020-04-27 02:03
I sent you a message on Kakao Talk! I want you to check it out.

**Closed as completed** 2020-04-27 11:42 UTC
